# Generated by Django 4.0.1 on 2022-01-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_request_notification_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.CharField(choices=[('LIKE', 'Like'), ('DISLIKE', 'Dislike'), ('COMMENT', 'Comment')], max_length=50),
        ),
    ]
