# Generated by Django 4.0.1 on 2022-01-10 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='notification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.notification'),
        ),
    ]
