# Generated by Django 4.0.1 on 2022-01-10 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_alter_request_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='notification',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.notification'),
        ),
    ]
